fix(53): Fix json data to use bulk import script
leonarf/VCA4D pull request #103
Opened 2024-09-02 16:47 UTC by maximepiard

Ticket: #53

## Contexte

On veut pouvoir changer le script d'import sans avoir a manuellement re-importer tout

## Plan de PRs

- [102](https://github.com/leonarf/VCA4D/pull/102): Création du script de re-import en groupe
- :dart: **Cette PR**: Correction des jsons, xlsx et paramétrage du script d'import
- PR suivante: Meilleure gestion des données d'emplois

## Changements

- On ajoute manuellement `?` a la fin de la question sociale 1.1.3. dans le script d'import. C'est le seul changement "exceptionnel" qu'on fait
- On arrete de remplir "2020" comme année par défaut des études sociales
- On renome les fichiers et dossiers des études pour qu'ils correspondent aux noms de leur pays/études. Dès lors, l'utilisateur voit dans l'excel +- ce qui sera affiché sur le site.
- On répare quelques excels
  - exemple: on ajoute la devise directement dans l'excel Burundi milk

2024-09-02 16:49 UTC, maximepiard commented
@leonarf comme discuté, j'ai essayé de faire le plus simple possible. 2 choses sont passé à la trappe

- Pas moyen de modifier 2 fichiers de "fishery" a "fisheries". je vais les redemander au client via Marion.
  - Entre temps, on doit supprimer les changement de data.json que mon script induit :confused: 
- Je n'ai pas touché les "Title" des études, meme si ça ne doit pas etre utilisé. Car j'ai atteint mon but: le script d'import massifs ne modifie plus les json => les valeurs des xlsx vs json sont cohérentes :tada: 

Dis moi si tu as des remarques :slightly_smiling_face:

2024-09-03 07:22 UTC, leonarf requested changes
Il faut corriger l'excel burundi milk economic pour que le json contienne toujours les nombres d'acteurs

2024-09-03 07:22 UTC, leonarf commented on data/fisheries-gambia/fisheries-gambia-social.json
> +  "commodity": "Fisheries",
J'ai l'impression de comprendre qu'on met le nom du pays slugify maintenant, mais pour la commodity on met le pretty-name?

2024-09-03 07:22 UTC, leonarf commented on data/freshwater-aquaculture-georgia/freshwater-aquaculture-georgia-social.json
> +              "comment": "Based on the consultation with farmers, decisions of how to spend household income is negotiated between women and men. Decisions about expenses related to the aquaculture f
J'imagine que si on lance le script sous windows ou sous linux, ou si on modifie le fichier excel sous linux ou sous windows, les fins de lignes seront peut-être changé comme ici. Je ne sais pas si ça vaut le coup, mais on pourrait faire un .trim() sur les string des questions pour ne pas garder les fin de ligne ni les espaces en début ou fin.

2024-09-03 07:22 UTC, leonarf commented on data/milk-burundi/milk-burundi-eco.json
> +        "numberOfActors": 0,
Je ne pense pas que ça soit normal que le nombre d'acteur tombe à zéro dans cette étude. À mon avis il y a une correction à faire dans le fichier excel.

2024-09-03 07:22 UTC, leonarf commented on src/utils/format.js
> +  .replace(/[^\w|\s-]/g, '')
J'imagine que la modification de cette regex a à voir avec la commodity "mango|lime' mais je n'ai pas vu de modification de cette commodity du coup je ne comprend pas trop cette modif

2024-09-03 08:09 UTC, maximepiard commented on src/utils/format.js
> +  .replace(/[^\w|\s-]/g, '')
@leonarf  En fait, si on ne modifie pas la regex, le script veut modifier la commodité en `mangolime`, ce qu'on ne veut pas. 
Donc on modifie la regex, ce qui confirme nos changement manuels sur le json d'étude.

2024-09-03 08:09 UTC, maximepiard commented on data/milk-burundi/milk-burundi-eco.json
> +        "numberOfActors": 0,
@leonarf Bien vu :eagle: ! Merci pour la relecture

En effet, le nom de la colonne n'était pas bon. => [`088d90f` (#103)](https://github.com/leonarf/VCA4D/pull/103/commits/088d90f1d794f26ff7301961f2930e70bbf00f8a)

2024-09-03 08:10 UTC, maximepiard commented on data/fisheries-gambia/fisheries-gambia-social.json
> +  "commodity": "Fisheries",
@leonarf c'est ça. Ce n'est pas très uniforme mais ça marche bien. 

Je pense qu'on doit plutot se baser sur le `product` qui est renseigné dans data.json ([ici](https://github.com/leonarf/VCA4D/blob/b4103204341b9c75918f2acd8f7dceae20cf3ecb/data/data.json#L262)), qui lui est lowercase et correspond aux autres "clés" produits de data.json.

2024-09-03 08:10 UTC, maximepiard commented on data/freshwater-aquaculture-georgia/freshwater-aquaculture-georgia-social.json
> +              "comment": "Based on the consultation with farmers, decisions of how to spend household income is negotiated between women and men. Decisions about expenses related to the aquaculture f
@leonarf Bonne idée ! 

- Ajout du trim:  [`8139be3` (#103)](https://github.com/leonarf/VCA4D/pull/103/commits/8139be3cc7710f89bee52a07f2fe72aa09591c01)
- Run du script pour mettre les données à jour: [`83d1742` (#103)](https://github.com/leonarf/VCA4D/pull/103/commits/83d17421d06562ab32d1918e2d9ef31dee279de3)

2024-09-03 08:50 UTC, leonarf approved these changes

2024-09-03 08:50 UTC, leonarf commented on src/utils/import/social.js
> +      const QUESTION_WITHOUT_INTEROGATION = "1.1.3 To what extent do workers benefit from enforceable and fair contracts ";
Avec le trim des questions sociales, je me demande si ce bout de code qui ajoute un '?' à la fin de la question fonctionne toujours.

2024-09-03 08:54 UTC, maximepiard commented on src/utils/import/social.js
> +      const QUESTION_WITHOUT_INTEROGATION = "1.1.3 To what extent do workers benefit from enforceable and fair contracts ";
@leonarf Il marche encore, car on trim a posteriori :blush: 

cf cette ligne dans le commit qui run le script: rien n'a changé [`83d1742` (#103)](https://github.com/leonarf/VCA4D/pull/103/commits/83d17421d06562ab32d1918e2d9ef31dee279de3#diff-093008760e6dc3610893282e173b984be354cc9b1dd5c1c757b78d0bf87fbd9dL29)

2024-09-03 10:31 UTC, merged